version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: schedule_messages
     
    env_file: .env
    ports:
      - "5432:5432"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - ./:/app
    entrypoint: yarn start
    ports:
      - "8080:8080"
 
    env_file: .env
    environment:
       WAIT_HOSTS: db:5432
    depends_on:
      - db

